# Generated by Django 5.1.6 on 2025-05-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_subcategory_options_subcategory_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Телеграмм id')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.CharField(max_length=100, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organisation', to='bot.organisationcategory')),
            ],
        ),
    ]
